// ActionType.js
export const FETCH_STOCK_REQUEST = "FETCH_STOCK_REQUEST";
export const FETCH_STOCK_SUCCESS = "FETCH_STOCK_SUCCESS";
export const FETCH_STOCK_FAILURE = "FETCH_STOCK_FAILURE";

export const FETCH_STOCK_BY_ID_REQUEST = "FETCH_STOCK_BY_ID_REQUEST";
export const FETCH_STOCK_BY_ID_SUCCESS = "FETCH_STOCK_BY_ID_SUCCESS";
export const FETCH_STOCK_BY_ID_FAILURE = "FETCH_STOCK_BY_ID_FAILURE";
