// ActionType.js
export const FETCH_MARKET_NEWS_REQUEST = "FETCH_MARKET_NEWS_REQUEST";
export const FETCH_MARKET_NEWS_SUCCESS = "FETCH_MARKET_NEWS_SUCCESS";
export const FETCH_MARKET_NEWS_FAILURE = "FETCH_MARKET_NEWS_FAILURE";
