// actionTypes.js
export const FETCH_MARKET_STATUS_REQUEST = 'FETCH_MARKET_STATUS_REQUEST';
export const FETCH_MARKET_STATUS_SUCCESS = 'FETCH_MARKET_STATUS_SUCCESS';
export const FETCH_MARKET_STATUS_FAILURE = 'FETCH_MARKET_STATUS_FAILURE';
