// Get Watchlist
export const GET_USER_WATCHLIST_REQUEST = "GET_USER_WATCHLIST_REQUEST";
export const GET_USER_WATCHLIST_SUCCESS = "GET_USER_WATCHLIST_SUCCESS";
export const GET_USER_WATCHLIST_FAILURE = "GET_USER_WATCHLIST_FAILURE";

// Add Stock to Watchlist
export const ADD_STOCK_TO_WATCHLIST_REQUEST = "ADD_STOCK_TO_WATCHLIST_REQUEST";
export const ADD_STOCK_TO_WATCHLIST_SUCCESS = "ADD_STOCK_TO_WATCHLIST_SUCCESS";
export const ADD_STOCK_TO_WATCHLIST_FAILURE = "ADD_STOCK_TO_WATCHLIST_FAILURE";


//Remove stock from watchlist
export const DELETE_STOCK_TO_WATCHLIST_REQUEST="DELETE_STOCK_TO_WATCHLIST_REQUEST";
export const DELETE_STOCK_TO_WATCHLIST_SUCCESS="DELETE_STOCK_TO_WATCHLIST_SUCCESS";
export const DELETE_STOCK_TO_WATCHLIST_FAILURE="DELETE_STOCK_TO_WATCHLIST_FAILURE";