
export const FETCH_RECOMMENDED_STOCKS_REQUEST = "FETCH_RECOMMENDED_STOCKS_REQUEST";
export const FETCH_RECOMMENDED_STOCKS_SUCCESS = "FETCH_RECOMMENDED_STOCKS_SUCCESS";
export const FETCH_RECOMMENDED_STOCKS_FAILURE = "FETCH_RECOMMENDED_STOCKS_FAILURE";
