// User Registration
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// User Login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// Two-Step Authentication Login
export const LOGIN_TWOSTEP_REQUEST = "LOGIN_TWOSTEP_REQUEST";
export const LOGIN_TWOSTEP_SUCCESS = "LOGIN_TWOSTEP_SUCCESS";
export const LOGIN_TWOSTEP_FAILURE = "LOGIN_TWOSTEP_FAILURE";

// Get User Information
export const GETUSER_REQUEST = "GETUSER_REQUEST";
export const GETUSER_SUCCESS = "GETUSER_SUCCESS";
export const GETUSER_FAILURE = "GETUSER_FAILURE";

// Send Verification OTP
export const SEND_VERIFICATION_OTP_REQUEST = "SEND_VERIFICATION_OTP_REQUEST";
export const SEND_VERIFICATION_OTP_SUCCESS = "SEND_VERIFICATION_OTP_SUCCESS";
export const SEND_VERIFICATION_OTP_FAILURE = "SEND_VERIFICATION_OTP_FAILURE";

// Enable Two-Step Authentication
export const ENABLE_TWOSTEP_AUTHENTICATION_REQUEST = "ENABLE_TWOSTEP_AUTHENTICATION_REQUEST";
export const ENABLE_TWOSTEP_AUTHENTICATION_SUCCESS = "ENABLE_TWOSTEP_AUTHENTICATION_SUCCESS";
export const ENABLE_TWOSTEP_AUTHENTICATION_FAILURE = "ENABLE_TWOSTEP_AUTHENTICATION_FAILURE";

// Verify OTP for Two-Step Authentication
export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

// Send Reset Password Request
export const SEND_RESET_PASSWORD_REQUEST = "SEND_RESET_PASSWORD_REQUEST";
export const SEND_RESET_PASSWORD_SUCCESS = "SEND_RESET_PASSWORD_SUCCESS";
export const SEND_RESET_PASSWORD_FAILURE = "SEND_RESET_PASSWORD_FAILURE";

// Verify Reset Password Request (OTP for password reset)
export const VERIFY_RESETPASSWORD_REQUEST = "VERIFY_RESETPASSWORD_REQUEST";
export const VERIFY_RESETPASSWORD_SUCCESS = "VERIFY_RESETPASSWORD_SUCCESS";
export const VERIFY_RESETPASSWORD_FAILURE = "VERIFY_RESETPASSWORD_FAILURE";

export const LOGOUT="LOGOUT"
