// src/State/StockList/ActionType.js
export const FETCH_STOCKLIST_REQUEST = 'FETCH_STOCKLIST_REQUEST';
export const FETCH_STOCKLIST_SUCCESS = 'FETCH_STOCKLIST_SUCCESS';
export const FETCH_STOCKLIST_FAILURE = 'FETCH_STOCKLIST_FAILURE';
